name = "Anodyne"
home = "https://discord.com/channels/731205301247803413/1121290232688545792"
default_url = "https://github.com/PixieCatSupreme/ArchipelagoAno/releases/download/v{{version}}/anodyne.apworld"

[versions]
"0.1.7" = {}
"0.1.9" = {}
"0.2.3" = {}
"0.2.4" = {}
