name = "Ape Escape"
home = https://discord.com/channels/731205301247803413/1168645708103028856

[versions]
"0.6.5" = { "url" = "https://github.com/Thedragon005/Archipelago-Ape-Escape/releases/download/v0.6.5/apeescape.apworld" }