name = "Banjo-Tooie"
home = "https://discord.com/channels/731205301247803413/1135352499172286505"

[versions]
"4.5.1" = { url = "https://github.com/jjjj12212/Archipelago-BanjoTooie/releases/download/V4.5.1/banjo_tooie.apworld" }
"4.10.1" = { url = "https://github.com/jjjj12212/Archipelago-BanjoTooie/releases/download/V4.10.1/banjo_tooie.apworld" }
