name = "Cavern of Dreams"
home = "https://discord.com/channels/731205301247803413/1189647737210286080"
disabled = true # 25% failure rate, 1.10.2 is the same rate

[versions]
"1.10.1" = { url = "https://github.com/wu4/Archipelago/releases/download/v0-beta.10.1/cavern_of_dreams.apworld" }
