name = "Celeste (Open World)"
home = "https://discord.com/channels/731205301247803413/1364797357958631434"
default_url = "https://github.com/PoryGoneDev/Celeste-Archipelago-Open-World/releases/download/v{{version}}/celeste_open_world.apworld"

[versions]
"1.0.0" = {}
"1.0.1" = {}
"1.0.3" = {}
"1.0.4" = {}
