name = "Cursed Mario 64"
display_name = "Cursed Mario 64"
home = "https://discord.com/channels/731205301247803413/1494389627115536567"

[versions]
"0.1.5+hotfix" = { url = "https://github.com/IncidiousJacob/Cursed-Mario-64/releases/download/Filler/Cursed_Mario_64.apworld" }
