name = "Donkey Kong Country"
home = "https://discord.com/channels/731205301247803413/1364840991755997244"
default_url = "https://github.com/TheLX5/Archipelago/releases/download/dkc-v{{version}}/dkc.apworld"

[versions]
"1.0.5" = {}
