name = "Donkey Kong Country 2"
home = "https://discord.com/channels/731205301247803413/1023381145565548646"
default_url = "https://github.com/TheLX5/Archipelago/releases/download/dkc2-v{{version}}/dkc2.apworld"

[versions]
# This is just 2.0.0 but they overwrote the github release artifacts with a client side patch
# At the moment of writing this I don't have a better way of dealing with this
"2.0.0+patch1" = { url = "https://github.com/TheLX5/Archipelago/releases/download/dkc2-v2.0.0/dkc2.apworld" }
