name = "EarthBound"
home = "https://discord.com/channels/731205301247803413/1077266688657068032"

[versions]
"4.2.1" = { url = "https://github.com/PinkSwitch/Archipelago/releases/download/earthboundap4.2.1/earthbound.apworld" }
