name = "Frogmonster"
home = "https://discord.com/channels/731205301247803413/1271323478779363398"

[versions]
"0.1.0" = { url = "https://github.com/Rooby-Roo/FrogmonsterAPWorld/releases/download/v0.1.0/frogmonster.apworld"}