name = "The Grinch"
home = "https://discord.com/channels/731205301247803413/1279837475338190999"
default_url = "https://github.com/MarioSpore/Grinch-AP/releases/download/v{{version}}/grinch.apworld"

[versions]
"1.0.2" = {}
"1.0.3" = {}
