name = "Hades"
home = "https://discord.com/channels/731205301247803413/1142985359563685898"
default_url = "https://github.com/NaixGames/Polycosmos/releases/download/{{version}}/hades.apworld"

[versions]
"0.12.3" = {}
"0.13.0-alpha+logic-fixes" = { local = "../apworlds/hades-0.13.0+logic-fixes.apworld" }
"0.13.0-alpha3" = { url = "https://github.com/NaixGames/Polycosmos/releases/download/pre-0.13.0/hades.apworld" }
