name = "Haste"
home = "https://discord.com/channels/731205301247803413/1356638437872111687"
default_url = "https://github.com/WritingHusky/haste_apworld/releases/download/v{{version}}/haste.apworld"

[versions]
"0.2.1" = { local = "../apworlds/haste-0.2.1.apworld" }
