name = "Into the Breach"
home = "https://github.com/Ishigh1/ITB-randomizer-for-AP"
default_url = "https://github.com/Ishigh1/ITB-randomizer-for-AP/releases/download/v{{version}}/into_the_breach.apworld"

[versions]
# Apworld is in `libs.7z/worlds`
"0.15.1" = { local = "../apworlds/into_the_breach-0.15.1.apworld" }
"0.15.12" = {}
