name = "Into the Breach"
home = "https://github.com/Ishigh1/ITB-randomizer-for-AP"

[versions]
"0.15.1" = { local = "../apworlds/into_the_breach-0.15.1.apworld" }
"0.15.12" = { url = "https://github.com/Ishigh1/ITB-randomizer-for-AP/releases/download/v0.15.12/into_the_breach.apworld" }
