name = "Keymaster's Keep"
home = "https://discord.com/channels/731205301247803413/1321323711676284939"

[versions]
"0.0.7" = { url = "https://github.com/SerpentAI/Archipelago/releases/download/kmk-pre-0007/keymasters_keep.apworld" }
"0.0.9" = { url = "https://github.com/SerpentAI/Archipelago/releases/download/kmk-pre-0009/keymasters_keep.apworld" }
# Modified version with silasary's kmk injector (https://github.com/silasary/kmk_injector) to include games in the apworld
"0.2.0+silasarybundle" = { local = "../apworlds/keymasters_keep-0.2.0+silasarybundle.apworld" }