name = "K-On! After School Live!!"
home = "https://discord.com/channels/731205301247803413/1388861873025323059"
default_url = "https://github.com/dannybonz/k-on_archipelago/releases/download/v{{version}}/kon.apworld"

[versions]
"1.1.1" = {}
