name = "Kirby Super Star"
home = "https://discord.com/channels/731205301247803413/1170152771043999764"
default_url = "https://github.com/Silvris/Archipelago/releases/download/kss_{{version}}/kss.apworld"

[versions]
"0.0.4" = {}
"0.1.1" = {}
