name = "Lies Of P"
home = "https://discord.com/channels/731205301247803413/1232017331232706680"
default_url = "https://github.com/Xtruh/LiesOfAP/releases/download/{{version}}/liesofp.apworld"

[versions]
"0.1.3" = {}
