name = "Loonyland"
home = "https://discord.com/channels/731205301247803413/1314639182655656016"
default_url = "https://github.com/AutomaticFrenzy/Archipelago/releases/download/{{version}}/loonyland.apworld"

[versions]
"0.2.1" = {}
