name = "Manual_DeadByDaylight-Killer-C35_nivomi"
display_name = "Manual: Dead By Daylight (Killer)"
home = "https://discord.com/channels/1097532591650910289/1219470964312510595"
default_url = "https://github.com/nivomi/deadbydaylight_manual_archipelago/releases/download/{{version}}/manual_deadbydaylight-killer-c35_nivomi.apworld"

[versions]
# When updating, this will probably not work and you'll need to change the name of the apworld, the name of the game and the default url
# This apworld targets a live online game, which chapters cannot be played after the next one is available
"0.0.6" = {}
