name = "Manual_DonaldDuckQuackAttack_1313e"
display_name = "Manual: Donald Duck Quack Attack"
home = "https://discord.com/channels/1097532591650910289/1334634929388130415"
default_url = "https://github.com/1313e/manual_donaldduckquackattack_1313e/releases/download/v{{version}}/manual_donaldduckquackattack_1313e.apworld"

[versions]
"0.0.2" = {}
