name = "Manual_Roguecraft_ConnorMiner"
display_name = "Manual: Roguecraft"

[versions]
"0.0.5" = { local = "../apworlds/manual_roguecraft_connorminer-0.0.5.apworld" }
"0.0.6" = { local = "../apworlds/manual_roguecraft_connorminer-0.0.6.apworld" }
