name = "Manual_NightmareKart_LOLZ"
display_name = "Manual: Nightmare Kart"
home = "https://discord.com/channels/1097532591650910289/1333827572462784572"

[versions]
"0.0.1" = { local = "../apworlds/manual_nightmarekart_lolz-0.0.1.apworld" }
