name = "Manual_FNFMods_Honk"
display_name = "Manual: Friday night Funkin' modded"
home = "https://discord.com/channels/1097532591650910289/1242936795570638918/1401269576175456366"

[versions]
"0.0.1" = { local = "../apworlds/manual_fnfmods_honk-0.0.1.apworld" }
