name = "Manual_guitarhero2_nyvgf"
display_name = "Manual: Guitar Hero 2"
home = "https://discord.com/channels/1097532591650910289/1215381088625762364"

[versions]
"0.0.2+zeenobae" = { local = "../apworlds/manual_guitarhero2_nyvgf-0.0.2+zeenobae.apworld" }
