name = "manual_goldeneye007_vincentssin"
home = "https://discord.com/channels/1097532591650910289/1284148581330190450"
display_name = "Manual: Goldeneye007"
default_url = "https://github.com/VincentsSin/Goldeneye007-Maunual_AP/releases/download/v{{version}}/manual_goldeneye007_vincentssin.apworld"

[versions]
"1.3.1" = {}
