name = "Manual_PeggleNights_Freezinater"
display_name = "Manual: Peggle Nights"
home = "https://discord.com/channels/1097532591650910289/1235014210895741070"

[versions]
"0.0.6" = { local = "../apworlds/manual_pegglenights_freezinater-0.0.6.apworld" }
