name = "Manual_SoundVoltex_v2_MapleLeaf"
display_name = "Manual: Sound Voltex"
home = "https://discord.com/channels/1097532591650910289/1414082550711975986"

[versions]
"0.2.0" = { local = "../apworlds/manual_soundvoltex_v2_mapleleaf-0.2.0.apworld" }
