display_name = "Manual: Euro Truck Simulator 2 (dopin)"
name = "Manual_ETS2_dopin"

[versions]
"0.1.0" = { local = "../apworlds/manual_ets2_dopin-0.1.0.apworld" }
"0.1.1" = { local = "../apworlds/manual_ets2_dopin-0.1.1.apworld" }
