display_name = "Manual: Powerwash Simulator"
name = "Manual_PowerwashSimulator_hallojasper"
home = "https://discord.com/channels/1097532591650910289/1181412855187243079"
default_url = "https://github.com/hallojasper/Powerwash-Simulator-Archipelago-Manual-Randomizer/releases/download/v{{version}}/manual_powerwashsimulator_hallojasper.apworld"

[versions]
"0.1.7" = {}
"0.1.8" = {}
"0.2.0" = {}
"0.2.1" = {}
