name = "Manual_BandHero_GWAF"
display_name = "Manual: Band Hero"
home = "https://discord.com/channels/1097532591650910289/1407113766969016422"

[versions]
"1.0.0" = { url = "https://github.com/GirlWithoutAFairy/Band-Hero-Manual-for-Archipelago/releases/download/v1.0/manual_bandhero_gwaf.apworld" }
