display_name = "Manual: Final Fantasy XIV"
name = "Manual_FFXIV_Silasary"
home = "https://discord.com/channels/1097532591650910289/1187584337877684294"

[versions]
"0.14.0" = { url = "https://github.com/silasary/APxiv/releases/download/0.14/manual_ffxiv_silasary.apworld"}
