name = "Manual_ResidentEvil4_VincentsSin"
home = "https://discord.com/channels/1097532591650910289/1297382888614006859"
display_name = "Manual: Resident Evil 4"
default_url = "https://github.com/VincentsSin/Resident-Evil-4-Manual-AP/releases/download/v{{version}}/manual_residentevil4_vincentssin.apworld"

[versions]
"1.2.0" = {}
# 2.0.0 got its artifacts changed at least once after inclusion
"2.0.0+hotfix1" = { url = "https://github.com/VincentsSin/Resident-Evil-4-Manual-AP/releases/download/v2.0.0/manual_residentevil4_vincentssin.apworld" }
