name = "Manual_BattleBlockTheater_commanderdot"
display_name = "Manual: BattleBlock Theater"
home = "https://discord.com/channels/1097532591650910289/1371605100178440263"

[versions]
"1.0.0" = { url = "https://github.com/commanderdot/ManualBattleBlockTheater/releases/download/v1.0/manual_battleblocktheater_commanderdot.apworld" }
