name = "Manual_RobloxDecayingWinter_ShadowWhelm"
display_name = "Manual: Roblox Decaying Winter"
home = "https://discord.com/channels/1097532591650910289/1222398529486716929"

[versions]
"0.0.1" = { local = "../apworlds/manual_robloxdecayingwinter_shadowwhelm-0.0.1.apworld" }
