name = "Manual_UmamusumePrettyDerby_Quindo"
display_name = "Manual: Umamusume: Pretty Derby"
home = "https://discord.com/channels/1097532591650910289/1404922064741077012"

[versions]
"0.0.2" = { url = "https://raw.githubusercontent.com/QuindoHL/ManualPrettyDerby/8d720a3506514c1469633a2aa33351cbb052031d/manual_umamusumeprettyderby_quindo.apworld" }
