name = "Manual_JumpUltimateStars_Pizzaking405"
display_name = "Manual: Jump Ultimate Stars"
home = "https://discord.com/channels/1097532591650910289/1278498367399526472"

[versions]
"3.5.0" = { url = "https://github.com/pizzaking405/Jump-Ultimate-Stars-Manual-Archipelago/releases/download/v3.5/manual_jumpultimatestars_pizzaking405.apworld" }
