name = "manual_goldeneye007_vincentssin"
display_name = "Manual: Goldeneye007"
home: "https://github.com/VincentsSin/Goldeneye007-Maunual_AP"

[versions]
"1.3.0" = { url = "https://github.com/VincentsSin/Goldeneye007-Maunual_AP/releases/tag/v1.3.0"}

"1.2.0" = {url = "https://github.com/VincentsSin/Goldeneye007-Maunual_AP/releases/tag/v1.2.0"}

"1.1.1" = { url = "https://github.com/VincentsSin/Goldeneye007-Maunual_AP/releases/tag/v1.1.1"}

"1.1.0" = { url = "https://github.com/VincentsSin/Goldeneye007-Maunual_AP/releases/tag/v1.1.0"}

"1.0" = { url = "https://github.com/VincentsSin/Goldeneye007-Maunual_AP/releases/tag/v1.0"}




