name = "Manual_TMNF_dopin"
display_name = "Manual: Trackmania Nations Forever"
home = "https://discord.com/channels/1097532591650910289/1329792432635908097"

[versions]
"0.0.1" = { local = "../apworlds/manual_tmnf_dopin-0.0.1.apworld" }
