name = "Manual_DeadByDaylight-Killer-C34_nivomi"
display_name = "Manual: Dead By Daylight (Killer)"
home = "https://discord.com/channels/1097532591650910289/1219470964312510595"
default_url = "https://github.com/nivomi/deadbydaylight_manual_archipelago/releases/download/{{version}}/manual_deadbydaylight-killer-c34_nivomi.apworld"

[versions]
"0.0.5" = {}
