display_name = "Manual: Buckshot Roulette"
name = "Manual_BuckshotRoulette_WolfBoi008"
home = "https://discord.com/channels/1097532591650910289/1271213919259594863"
tags = ["ad"]

[versions]
"1.2.0a" = { url = "https://github.com/WolfBoi008/Buckshot-Roulette/releases/download/1.2.0a/manual_buckshotroulette_wolfboi008.apworld" }
