display_name = "Manual: Final Fantasy XIV"
name = "Manual_FFXIV_Silasary"
home = "https://discord.com/channels/1097532591650910289/1187584337877684294"
default_url = "https://github.com/silasary/APxiv/releases/download/{{version}}/manual_ffxiv_silasary.apworld"

[versions]
"0.14" = {}
