name = "Manual_PlatinumBattleZone_Linneus"
display_name = "Manual: Platinum Battle Zone Challenge"
home = "https://discord.com/channels/1097532591650910289/1400667209172517046"
default_url = "https://github.com/Linneus/Platinum-Battle-Zone-Challenge/releases/download/{{version}}/manual_platinumbattlezone_linneus.apworld"

[versions]
"1.0.3" = {}
"1.0.4" = {}
