name = "Manual_Phasmophobia_TinMines"
display_name = "Manual: Phasmophobia"
home = "https://discord.com/channels/1097532591650910289/1238914721227345990"

[versions]
"0.0.1" = { local = "../apworlds/manual_phasmophobia_tinmines-0.0.1.apworld" }
