name = "Metroid Prime"
home = "https://discord.com/channels/731205301247803413/1172631093837570068"
# XXX: When updating, rezip with the LICENSE

[versions]
"0.3.3" = { local = "../apworlds/metroidprime-0.3.3.apworld" }
"0.4.5" = { local = "../apworlds/metroidprime-0.4.5.apworld" }
