name = "Metroid Prime"
home = "https://discord.com/channels/731205301247803413/1172631093837570068"
# XXX: When updating, rezip with the LICENSE

[versions]
"0.4.5" = { local = "../apworlds/metroidprime-0.4.5.apworld" }
"0.4.8" = { local = "../apworlds/metroidprime-0.4.8.apworld" }
"0.4.9" = { local = "../apworlds/metroidprime-0.4.9.apworld" }
"0.5.0" = { local = "../apworlds/metroidprime-0.5.0.apworld" }
