name = "Monster Sanctuary"
home = "https://discord.com/channels/731205301247803413/1217944663864901632"
default_url = "https://github.com/Gtaray/archipelago-monstersanctuary/releases/download/v{{version}}/monster_sanctuary.apworld"

[versions]
"1.3.4" = {}
"1.3.2+hotfix1" = { url = "https://github.com/Gtaray/archipelago-monstersanctuary/releases/download/v1.3.2/monster_sanctuary.apworld" }
"1.3.0" = {}
"1.2.1" = {}
"1.2.0" = {}
"1.3.5" = {}
