name = "Pizza Tower"
home = "https://discord.com/channels/731205301247803413/1079671816257277972"

[versions]
"1.0.0" = { url = "https://github.com/unsafetyskizzers/Archipelago/releases/download/release/pizza_tower.apworld" }
