name = "Pizza Tower"
home = "https://discord.com/channels/731205301247803413/1079671816257277972"
default_url = "https://github.com/unsafetyskizzers/Archipelago/releases/download/{{version}}/pizza_tower.apworld"

[versions]
"1.0.1" = {}
