name = "Pokemon Crystal"
home = "https://discord.com/channels/731205301247803413/1365127145709502575"
default_url = "https://github.com/gerbiljames/Archipelago/releases/download/{{version}}/pokemon_crystal.apworld"

[versions]
"4.0.0" = {}
"4.0.1" = {}
"4.0.2" = {}
"4.0.3" = {}
"4.0.5" = {}
"4.0.6" = {}
"4.0.7" = {}
"4.0.8" = {}
"4.0.9" = {}
"4.0.10" = {}
"4.0.11" = {}
"4.0.12" = {}
