name = "Pokemon Black and White"
home = "https://discord.com/channels/731205301247803413/1414928022854696991"
default_url = "https://github.com/BlastSlimey/PokemonBWAP/releases/download/{{version}}/pokemon_bw.apworld"

[versions]
"0.3.2" = {}