name = "Pokemon FireRed and LeafGreen"
home = "https://discord.com/channels/731205301247803413/1365127226533871718"
default_url = "https://github.com/vyneras/Archipelago/releases/download/{{version}}/pokemon_frlg.apworld"

[versions]
"0.8.7" = {}
"0.9.1" = {}
"0.9.2" = {}
"0.9.3" = {}
"0.9.4" = {}
"0.9.5" = {}
