name = "Rain World"
home = "https://discord.com/channels/731205301247803413/1136042293162418176"
default_url = "https://github.com/alphappy/ArchipelagoRW/releases/download/v{{version}}/rain_world.apworld"

[versions]
"1.3.1" = {}
"1.3.2" = {}
