name = "Rift Wizard"
home = "https://discord.com/channels/731205301247803413/1097001818564853770"
default_url = "https://github.com/TheBigSalarius/Archipelago/releases/download/v{{version}}/riftwizard.apworld"

[versions]
"1.3.1" = {}