name = "Sonic Heroes"
home = "https://discord.com/channels/731205301247803413/1234592520403423352"
default_url = "https://github.com/Ethicallogic-Archipelago/SonicHeroesArchipelago/releases/download/{{version}}/sonic_heroes.apworld"

[versions]
"1.0.2" = {}
"1.1.0" = {}
"1.1.3" = {}
"1.1.5" = {}
"1.1.7" = {}
"1.1.8" = {}
"1.1.9" = {}
"1.3.0" = {}
"1.4.0" = {}
