name = "The Binding of Isaac Repentance"
home = "https://discord.com/channels/731205301247803413/1044777889637339188"
default_url =  "https://github.com/NaveTK/Archipelago/releases/download/v{{version}}/tboir.apworld"

[versions]
"0.1.1" = {}
