name = "TCG Card Shop Simulator"
home = "https://discord.com/channels/731205301247803413/1302063649812250665/1374499143229374595"
default_url = "https://github.com/FyreDay/Archipelago-TCGCardShopSimulator/releases/tag/v0.3.2"

[versions]
"0.3.2" = {}

