name = "Touhou Koumakyou ~ the Embodiment of Scarlet Devil"
home = "https://discord.com/channels/1085716850370957462/1353408740480778270"
default_url = "https://github.com/Nepley/eosd-apworld/releases/download/v{{version}}/th06.apworld"

[versions]
"1.1.2" = {}
