name = "The Legend of Zelda - Oracle of Ages"
home = "https://discord.com/channels/731205301247803413/1279722186902601750"

[versions]
"0.2.4+0.5.1-fixes" = { local = "../apworlds/tloz_ooa-0.2.4+0.5.1-fixes.apworld" }
