name = "The Legend of Zelda - Oracle of Seasons"
home = "https://discord.com/channels/731205301247803413/1130706151303041054"

[versions]
"7.2.1+0.5.1-fixes" = { local = "../apworlds/tloz_oos-7.2.1+0.5.1-fixes.apworld" }
