name = "The Legend of Zelda - Oracle of Ages"
home = "https://discord.com/channels/731205301247803413/1279722186902601750"

[versions]
"0.4.3" = { url = "https://github.com/SenPierre/ArchipelagoOoA/releases/download/ooa_4_2/tloz_ooa.apworld" }
