[["test.general.test_options.TestOptions.test_pickle_dumps (game='Anodyne', option='overworld_gauntlet_gate')"]]
__expected__ = "error"
__version__ = ">=0.3.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Anodyne', option='overworld_fields_gate')"]]
__expected__ = "error"
__version__ = ">=0.3.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Anodyne', option='fields_terminal_gate')"]]
__expected__ = "error"
__version__ = ">=0.3.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Anodyne', option='beach_gauntlet_gate')"]]
__expected__ = "error"
__version__ = ">=0.3.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Anodyne', option='windmill_entrance_gate')"]]
__expected__ = "error"
__version__ = ">=0.3.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Anodyne', option='windmill_middle_gate')"]]
__expected__ = "error"
__version__ = ">=0.3.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Anodyne', option='windmill_top_gate')"]]
__expected__ = "error"
__version__ = ">=0.3.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Anodyne', option='suburb_gate')"]]
__expected__ = "error"
__version__ = ">=0.3.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Anodyne', option='cell_gate')"]]
__expected__ = "error"
__version__ = ">=0.3.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Anodyne', option='terminal_endgame_gate')"]]
__expected__ = "error"
__version__ = ">=0.3.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Anodyne', option='blank_postgame_gate')"]]
__expected__ = "error"
__version__ = ">=0.3.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Anodyne', option='nexus_north_final_gate')"]]
__expected__ = "error"
__version__ = ">=0.3.1"
