[["test.general.test_items.TestBase.test_item_links [Can generate with link replacement] (game='An Untitled Story')"]]
__expected__ = "error"
__version__ = ">=1.0.0-beta"

[["test.general.test_items.TestBase.test_item_links [Can generate without link replacement] (game='An Untitled Story')"]]
__expected__ = "error"
__version__ = ">=1.0.0-beta"
