[["test.general.test_items.TestBase.test_item_links [Can generate with link replacement] (game='Dome Keeper')"]]
__expected__ = "error"
__version__ = ">=1.1.4"

[["test.general.test_items.TestBase.test_item_links [Can generate without link replacement] (game='Dome Keeper')"]]
__expected__ = "error"
__version__ = ">=1.1.4"
