[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='generate_basic', game='Manual_LEGORockBand_GWAF')"]]
__expected__ = "fail"
__version__ = ">=0.0.1"

[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='pre_fill', game='Manual_LEGORockBand_GWAF')"]]
__expected__ = "fail"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_LEGORockBand_GWAF', option='Example_Toggle')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_LEGORockBand_GWAF', option='Example_Choice')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_LEGORockBand_GWAF', option='Example_Range')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_LEGORockBand_GWAF', option='DLC_enabled')"]]
__expected__ = "error"
__version__ = ">=0.0.1"
