[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='generate_basic', game='Manual_NightmareKart_LOLZ1190')"]]
__expected__ = "fail"
__version__ = ">=0.0.2"

[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='pre_fill', game='Manual_NightmareKart_LOLZ1190')"]]
__expected__ = "fail"
__version__ = ">=0.0.2"
