[["test.general.test_items.TestBase.test_item_name_group_conflict [Pokétch] (group_name='Pokétch', game_name='Manual_PlatinumBattleZone_Linneus')"]]
__expected__ = "fail"
__version__ = ">=1.0.3"

[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='generate_basic', game='Manual_PlatinumBattleZone_Linneus')"]]
__expected__ = "fail"
__version__ = ">=1.0.3"

[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='pre_fill', game='Manual_PlatinumBattleZone_Linneus')"]]
__expected__ = "fail"
__version__ = ">=1.0.3"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_PlatinumBattleZone_Linneus', option='require_dowsing_machine')"]]
__expected__ = "error"
__version__ = ">=1.0.3"
