[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='generate_basic', game='Manual_Diablo2_Maragan')"]]
__expected__ = "fail"
__version__ = ">=0.0.1"

[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='pre_fill', game='Manual_Diablo2_Maragan')"]]
__expected__ = "fail"
__version__ = ">=0.0.1"

[["test.general.test_locations.TestBase.test_location_group [GOAL] (group_name='GOAL', game_name='Manual_Diablo2_Maragan')"]]
__expected__ = "fail"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_Diablo2_Maragan', option='Example_Toggle')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_Diablo2_Maragan', option='Example_Choice')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_Diablo2_Maragan', option='Example_Range')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_Diablo2_Maragan', option='DLC_enabled')"]]
__expected__ = "error"
__version__ = ">=0.0.1"
