[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='generate_basic', game='Manual_guitarhero3_garbo')"]]
__expected__ = "fail"
__version__ = ">=1.3.0"

[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='pre_fill', game='Manual_guitarhero3_garbo')"]]
__expected__ = "fail"
__version__ = ">=1.3.0"
