[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_Roguecraft_ConnorMiner', option='Example_Toggle')"]]
__expected__ = "error"
__version__ = ">=0.0.5"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_Roguecraft_ConnorMiner', option='Example_Choice')"]]
__expected__ = "error"
__version__ = ">=0.0.5"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_Roguecraft_ConnorMiner', option='Example_Range')"]]
__expected__ = "error"
__version__ = ">=0.0.5"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_Roguecraft_ConnorMiner', option='DLC_enabled')"]]
__expected__ = "error"
__version__ = ">=0.0.5"
