[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='generate_basic', game='Manual_SonicXShadowGenerations_FlutterRazzo')"]]
__expected__ = "fail"
__version__ = ">=0.0.1"

[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='pre_fill', game='Manual_SonicXShadowGenerations_FlutterRazzo')"]]
__expected__ = "fail"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_SonicXShadowGenerations_FlutterRazzo', option='enable_sonic_s_ranks')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_SonicXShadowGenerations_FlutterRazzo', option='enable_sonic_challenge_s_ranks')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_SonicXShadowGenerations_FlutterRazzo', option='enable_shadow_s_ranks')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_SonicXShadowGenerations_FlutterRazzo', option='enable_shadow_challenge_s_ranks')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_SonicXShadowGenerations_FlutterRazzo', option='enable_red_star_ring_checks')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_SonicXShadowGenerations_FlutterRazzo', option='enable_shadow_collection_key_checks')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_SonicXShadowGenerations_FlutterRazzo', option='enable_sonic_boss_s_ranks')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_SonicXShadowGenerations_FlutterRazzo', option='enable_shadow_boss_s_ranks')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_SonicXShadowGenerations_FlutterRazzo', option='enable_chao_hunt_checks')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_SonicXShadowGenerations_FlutterRazzo', option='enable_sonic_generations')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_SonicXShadowGenerations_FlutterRazzo', option='enable_shadow_generations')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_SonicXShadowGenerations_FlutterRazzo', option='enable_movie_update_dlc')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_SonicXShadowGenerations_FlutterRazzo', option='enable_rocket_parts')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_SonicXShadowGenerations_FlutterRazzo', option='enable_shadow_hard_bosses')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_SonicXShadowGenerations_FlutterRazzo', option='enable_sonic_hard_bosses')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_SonicXShadowGenerations_FlutterRazzo', option='enable_shadow_hard_missions')"]]
__expected__ = "error"
__version__ = ">=0.0.1"
