[["test.general.test_items.TestBase.test_create_item"]]
item_name = "3x Star Pieces"
game_name = "Paper Mario"
__expected__ = "fail"
__version__ = ">=0.4.1,<0.4.2"

[["test.general.test_items.TestBase.test_create_item"]]
item_name = "3x Star Pieces"
game_name = "Paper Mario"
__expected__ = "fail"
__version__ = ">=0.4.4"
