[["test.general.test_items.TestBase.test_item_links [Can generate with link replacement] (game='Spinball')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_items.TestBase.test_item_links [Can generate without link replacement] (game='Spinball')"]]
__expected__ = "error"
__version__ = ">=0.0.1"
