---
trust-domain: "ap"
task-priority: low

taskgraph:
  cached-task-prefix: "ap.v2.archipelago-index"
  repositories:
    archipelago_index:
      name: "Archipelago-index"

  register: src:register

workers:
  aliases:
    linux-small:
      provisioner: ap
      implementation: docker-worker
      os: linux
      worker-type: linux-test
    linux-medium:
      provisioner: ap
      implementation: docker-worker
      os: linux
      worker-type: linux-medium
    images:
      provisioner: ap
      implementation: docker-worker
      os: linux
      worker-type: linux-medium
