---
trust-domain: "ap"
task-priority: low

taskgraph:
  cached-task-prefix: "ap.archipelago-index"
  repositories:
    archipelago_index:
      name: "Archipelago-index"

  register: src:register
  decision-parameters: src:get_decision_parameters

workers:
  aliases: {}
