---
trust-domain: "ap"
task-priority: low

taskgraph:
  cached-task-prefix: "ap.archipelago-index"
  repositories:
    archipelago_index:
      name: "Archipelago-index"

  register: src:register

workers:
  aliases: {}
